### ISSUE TITLE
Neither Thallium not Telescopic Sight are affected by luck

### ISSUE THREAD

**Issue by gaforb** [swuff-star/LostInTransit#13]
Tested by giving myself 999 clovers and shooting for a bit. Also I checked the actual code.

**Comment by Nebby1999** [comment]
Inteded. both items are incredibly powerful by themselves and shouldnt be affected by luck.

**Comment by swuff-star** [comment]
Thallium can be increased by luck fine. Telescopic sight... no, lol.

**Comment by gaforb** [comment]
Make it a config option?

**Comment by swuff-star** [comment]
Don't see why not. Will do it next time I open up the project.

**Comment by Nebby1999** [comment]
ew

**Comment by sammyros** [comment]
Gaforb you madlad you just got swuff to make a config for Telescopic sight to be affected by luck my god.
