### ISSUE TITLE
Volatile aspect has an error message in its logbook

### ISSUE THREAD

**Issue by Flamewarp** [swuff-star/LostInTransit#16]
![image](https://user-images.githubusercontent.com/36282563/150701693-7ac55fa8-3c30-446e-90d2-df95fe7181f3.png)

**Comment by swuff-star** [comment]
how did you even get it in logbook to begin with lol

**Comment by swuff-star** [comment]
someone in discord says wolfo qol mod adds aspects to the log - do the other aspects have entries of any kind? or the just the default placeholder?

**Comment by Flamewarp** [comment]
Ah, you're right. I do use wolfo, and the basegame aspects seem to just have the basic datascraper message. So not an issue with LIT necessarily.

**Comment by swuff-star** [comment]
got it - i'll just remove the lang token so it'll be consistent. ty
