### ISSUE TITLE
Logbook just straight up broken.

### ISSUE THREAD

**Issue by sammyros** [swuff-star/LostInTransit#21]
All i have is the mod and all its dependencies installed, the logbook decides to commit die and not load.

[LogOutput.txt](https://github.com/swuff-star/LostInTransit/files/8532853/LogOutput.txt)

**Comment by swuff-star** [comment]
![unknown-433](https://user-images.githubusercontent.com/63352264/164528308-65260e87-d56a-4c16-af13-72d177442b98.png)

**Comment by sammyros** [comment]
Aw shit, thanks
