### ISSUE TITLE
Guardian's heart

### ISSUE THREAD

**Issue by FORCED-REASSEMBLY** [swuff-star/LostInTransit#22]
Guardian's heart does not give you the shield until you reach the next stage sometimes.

**Comment by FORCED-REASSEMBLY** [comment]
Oh. I do wonder what would cause it since I dont have too many item mods that could mess with it.

**Comment by swuff-star** [comment]
I'm not sure either, but it runs a recalculatestats when picked up, and the additional shield is also handled via the same API. ¯\_(ツ)_/¯
