### ISSUE TITLE
Repulsion Armour buff lasting longer than intended

### ISSUE THREAD

**Issue by rivercityrancid** [swuff-star/LostInTransit#28]
After the initial intended duration of the active buff (3s, +1.5s on stack), the player receives the buff again immediately afterwards for about half of the original duration, without needing to take any further hits e.g if you get hit 6 times at 1 stack of Repulsion Armour you receive a 3s buff, followed by a ~1.5s buff
- Tested and behaviour is consistent with stacking (e.g at 7 stacks you receive a 12s buff after getting hit 6 times, followed by an additional 6s buff)
- The cooldown for Repulsion Armour returns at the same time the additional buff occurs

[LogOutput.log](https://github.com/swuff-star/LostInTransit/files/9793043/LogOutput.log)

hope I actually did this right lmao

**Comment by swuff-star** [comment]
> hope I actually did this right lmao

you did wonderful!!! will have this fixed tonight :)
