### ISSUE TITLE
Golden Gun Not Updating With New Stacks

### ISSUE THREAD

**Issue by drp527** [swuff-star/LostInTransit#29]
Seen consistently when I've actually been looking for it, Golden Gun's max damage boost only seems to update on loading the next stage. The initial stack will immediately bring you from 0 to 40 maximum, but if you get a second one after that 40 will stay the cap until you advance to a new stage. Same with getting any additional stacks on that new stage, the cap will not rise until you load out and into another one.
[LogOutput.log](https://github.com/swuff-star/LostInTransit/files/9793130/LogOutput.log)

**Comment by swuff-star** [comment]
fixed with imminent next update
