### ISSUE TITLE
Guardian's Heart Invulnerability

### ISSUE THREAD

**Issue by drp527** [swuff-star/LostInTransit#31]
Picking up guardian's heart not only stops me from taking damage, but also stops me from using any health cost interactables on the map. It's kind of funny watching hit visuals play repeatedly for a solid few seconds or lemurian fireballs bank off of me though.
[LogOutput.log](https://github.com/swuff-star/LostInTransit/files/9804863/LogOutput.log)

**Comment by swuff-star** [comment]
oh yeah this has been fixed a while oops
